import { RateLimiter, MINUTE } from "@convex-dev/rate-limiter";
// @ts-ignore - components are generated by Convex during dev
import { components } from "./_generated/api";

// Rate limit configuration
const RATE_LIMIT_CONFIG = {
  // Limit phase generation: 10 per minute per user
  generatePhase: {
    kind: "token bucket" as const,
    period: MINUTE,
    rate: 10,
    capacity: 15, // Allow bursts up to 15
  },
  // Limit question answering: 30 per minute per user
  generateQuestionAnswer: {
    kind: "token bucket" as const,
    period: MINUTE,
    rate: 30,
    capacity: 50, // Allow bursts up to 50
  },
  // Limit question generation: 10 per minute per user
  generateQuestions: {
    kind: "token bucket" as const,
    period: MINUTE,
    rate: 10,
    capacity: 15,
  },
  // Limit ZIP generation: 5 per minute per user
  generateProjectZip: {
    kind: "token bucket" as const,
    period: MINUTE,
    rate: 5,
    capacity: 8,
  },
  // Global limits to prevent abuse
  globalPhaseGen: {
    kind: "fixed window" as const,
    period: MINUTE,
    rate: 100, // 100 total per minute across all users
  },
  globalZipGen: {
    kind: "fixed window" as const,
    period: MINUTE,
    rate: 30,
  },
};

// Initialize rate limiter with Convex components
// This must be initialized once at module load time
export const rateLimiter = new RateLimiter(components.rateLimiter, RATE_LIMIT_CONFIG);
