/**
 * Phase Dependency Graph
 * 
 * Defines the dependency relationships between specification phases.
 * Used for staleness detection and generation ordering.
 */

export const PHASE_DEPENDENCIES: Record<string, string[]> = {
  constitution: [],
  brief: [],
  prd: ['brief', 'constitution'],
  domainModel: ['brief', 'constitution'],
  specs: ['prd', 'domainModel', 'constitution'],
  stories: ['specs', 'prd', 'constitution'],
  artifacts: ['specs', 'stories'],
  handoff: ['specs', 'stories', 'artifacts', 'constitution'],
};

/**
 * Returns all phases that depend (directly or transitively) on the changed phase.
 * Used to mark downstream phases as "stale" when an upstream phase is re-generated.
 */
export function getAffectedPhases(changedPhase: string): string[] {
  const affected = new Set<string>();

  function collect(phase: string): void {
    for (const [downstream, deps] of Object.entries(PHASE_DEPENDENCIES)) {
      if (deps.includes(phase) && !affected.has(downstream)) {
        affected.add(downstream);
        collect(downstream); // Transitive propagation
      }
    }
  }

  collect(changedPhase);
  return Array.from(affected);
}

/**
 * Validates that a phase can be generated by checking all dependencies are "ready".
 */
export function canGeneratePhase(
  phaseId: string,
  phaseStatuses: Record<string, string>,
): { canGenerate: boolean; blockedBy: string[] } {
  const deps = PHASE_DEPENDENCIES[phaseId] || [];
  const blockedBy = deps.filter(
    (dep) => phaseStatuses[dep] !== 'ready' && phaseStatuses[dep] !== 'skipped'
  );
  return {
    canGenerate: blockedBy.length === 0,
    blockedBy,
  };
}

/**
 * Returns the topological order of phases for sequential generation.
 */
export function getPhaseOrder(): string[] {
  return [
    'constitution',
    'brief',
    'prd',
    'domainModel',
    'specs',
    'stories',
    'artifacts',
    'handoff',
  ];
}

/**
 * Returns required upstream artifacts for a given phase's prompt context.
 */
export function getRequiredContext(phaseId: string): string[] {
  return PHASE_DEPENDENCIES[phaseId] || [];
}

/**
 * Validates that the dependency graph has no cycles.
 * Used for unit testing and runtime validation.
 */
export function validateDependencyGraph(): { valid: boolean; cycles: string[][] } {
  const cycles: string[][] = [];
  const visited = new Set<string>();
  const recursionStack = new Set<string>();

  function dfs(phase: string, path: string[]): void {
    if (recursionStack.has(phase)) {
      // Found a cycle
      const cycleStart = path.indexOf(phase);
      cycles.push(path.slice(cycleStart).concat([phase]));
      return;
    }

    if (visited.has(phase)) {
      return;
    }

    visited.add(phase);
    recursionStack.add(phase);

    const deps = PHASE_DEPENDENCIES[phase] || [];
    for (const dep of deps) {
      dfs(dep, [...path, phase]);
    }

    recursionStack.delete(phase);
  }

  for (const phase of Object.keys(PHASE_DEPENDENCIES)) {
    if (!visited.has(phase)) {
      dfs(phase, []);
    }
  }

  return { valid: cycles.length === 0, cycles };
}

/**
 * Returns phases grouped into batches that can run in parallel.
 * Each batch contains phases whose dependencies are all in earlier batches.
 * Skipped phases are treated as resolved so they don't block downstream phases.
 */
export function getParallelBatches(skippedPhases: string[] = []): string[][] {
  const remaining = new Set(
    Object.keys(PHASE_DEPENDENCIES).filter(p => !skippedPhases.includes(p))
  );
  const resolved = new Set(skippedPhases);
  const batches: string[][] = [];

  while (remaining.size > 0) {
    const batch: string[] = [];
    for (const phase of remaining) {
      const deps = PHASE_DEPENDENCIES[phase] || [];
      if (deps.every(d => resolved.has(d))) {
        batch.push(phase);
      }
    }
    if (batch.length === 0) break; // Safety: prevent infinite loop
    batch.forEach(p => {
      remaining.delete(p);
      resolved.add(p);
    });
    batches.push(batch);
  }

  return batches;
}

/**
 * Checks if a phase is downstream of another phase.
 */
export function isDownstreamOf(phase: string, potentialUpstream: string): boolean {
  const deps = PHASE_DEPENDENCIES[phase] || [];
  if (deps.includes(potentialUpstream)) {
    return true;
  }
  // Check transitive dependencies
  return deps.some((dep) => isDownstreamOf(dep, potentialUpstream));
}
