interface ClipboardFormatInput {
  title: string;
  content: string;
}

/**
 * Format spec content for Claude Code (CLAUDE.md style)
 */
export function formatForClaudeCode(input: ClipboardFormatInput): string {
  return `# ${input.title} — SpecForge Specification\n\n> Generated by SpecForge. Paste this into your CLAUDE.md or use as agent context.\n\n${input.content}\n`;
}

/**
 * Format spec content for Cursor (.cursorrules style)
 */
export function formatForCursor(input: ClipboardFormatInput): string {
  return `# Project: ${input.title}\n\n${input.content}\n`;
}

/**
 * Format spec content for GitHub Copilot (.github/copilot-instructions.md)
 */
export function formatForCopilot(input: ClipboardFormatInput): string {
  return `# ${input.title}\n\n${input.content}\n`;
}
