/**
 * SKILL.md Formatter for Agent-Native Artifacts
 *
 * Generates SKILL.md files following the Anthropic/agentskills.io specification.
 * These files allow AI agents (Claude Code, Cursor, etc.) to understand and
 * implement projects generated by SpecForge.
 *
 * Format: YAML frontmatter + Markdown body
 * Spec: https://agentskills.io
 */

// Note: Doc type not needed for this implementation
// import type { Doc } from '../../convex/_generated/dataModel';

/**
 * Input type for SKILL.md generation
 */
export interface SkillMdInput {
  project: {
    _id: string;
    title: string;
    description: string;
    createdAt: number;
  };
  artifacts: {
    brief?: string;
    constitution?: string;
    prd?: string;
    techSpec?: string;
    userStories?: string;
    handoff?: string;
  };
}

/**
 * Generates a SKILL.md file from project artifacts
 * Follows the agentskills.io specification
 */
export function generateSkillMd(input: SkillMdInput): string {
  const { project, artifacts } = input;
  const kebabName = kebabCase(project.title);

  // Parse constitution if available
  const constitution = artifacts.constitution
    ? parseConstitution(artifacts.constitution)
    : null;

  // Build YAML frontmatter
  const yamlFrontmatter = buildYamlFrontmatter(project, kebabName);

  // Build markdown content
  const markdownContent = buildMarkdownContent(
    project,
    artifacts,
    constitution,
  );

  return `${yamlFrontmatter}\n${markdownContent}`;
}

/**
 * Builds YAML frontmatter according to agentskills.io spec
 */
function buildYamlFrontmatter(
  project: SkillMdInput['project'],
  kebabName: string,
): string {
  return `---
name: ${kebabName}-specforge-handoff
description: Build ${project.title} from SpecForge specification
license: MIT
compatibility:
  - Claude Code
  - Cursor
  - Codex
  - Gemini CLI
  - GitHub Copilot
---`;
}

/**
 * Builds the main markdown content
 */
function buildMarkdownContent(
  project: SkillMdInput['project'],
  artifacts: SkillMdInput['artifacts'],
  constitution: ParsedConstitution | null,
): string {
  const sections: string[] = [];

  // Header
  sections.push(`# ${project.title} - Implementation Guide`);
  sections.push('');

  // Overview
  sections.push('## Project Overview');
  sections.push(project.description || 'No description available.');
  sections.push('');

  // Locked Constraints (from constitution)
  if (constitution?.lockedConstraints) {
    sections.push('## 🔒 Locked Constraints (Zero-Drift Rules)');
    sections.push(
      '**CRITICAL: You must NEVER violate these rules under any circumstance.**',
    );
    sections.push('');

    if (constitution.lockedConstraints.stateInvariants?.length) {
      sections.push('### State Invariants');
      constitution.lockedConstraints.stateInvariants.forEach((rule) => {
        sections.push(`- ${rule}`);
      });
      sections.push('');
    }

    if (constitution.lockedConstraints.domainRules?.length) {
      sections.push('### Domain Rules');
      constitution.lockedConstraints.domainRules.forEach((rule) => {
        sections.push(`- ${rule}`);
      });
      sections.push('');
    }

    if (constitution.lockedConstraints.securityProtocols?.length) {
      sections.push('### Security Protocols');
      constitution.lockedConstraints.securityProtocols.forEach((rule) => {
        sections.push(`- ${rule}`);
      });
      sections.push('');
    }
  }

  // Architecture (from constitution)
  if (constitution?.architecture) {
    sections.push('## Architecture');
    sections.push(`**Pattern:** ${constitution.architecture.pattern}`);
    if (constitution.architecture.rationale) {
      sections.push(`**Rationale:** ${constitution.architecture.rationale}`);
    }
    if (constitution.architecture.stateManagement) {
      sections.push(
        `**State Management:** ${constitution.architecture.stateManagement}`,
      );
    }
    if (constitution.architecture.apiDesign) {
      sections.push(`**API Design:** ${constitution.architecture.apiDesign}`);
    }
    sections.push('');
  }

  // Tech Stack (from constitution)
  if (constitution?.techStack) {
    sections.push('## Tech Stack');

    if (constitution.techStack.frontend) {
      sections.push(`### Frontend`);
      sections.push(
        `- Framework: ${constitution.techStack.frontend.framework}${constitution.techStack.frontend.version ? ` (${constitution.techStack.frontend.version})` : ''}`,
      );
      if (constitution.techStack.frontend.language) {
        sections.push(
          `- Language: ${constitution.techStack.frontend.language}`,
        );
      }
      sections.push('');
    }

    if (constitution.techStack.backend) {
      sections.push(`### Backend`);
      sections.push(`- Runtime: ${constitution.techStack.backend.runtime}`);
      sections.push(
        `- Framework: ${constitution.techStack.backend.framework}${constitution.techStack.backend.version ? ` (${constitution.techStack.backend.version})` : ''}`,
      );
      sections.push('');
    }

    if (constitution.techStack.database) {
      sections.push(`### Database`);
      sections.push(`- Type: ${constitution.techStack.database.type}`);
      sections.push(`- ORM: ${constitution.techStack.database.orm}`);
      if (constitution.techStack.database.hosting) {
        sections.push(`- Hosting: ${constitution.techStack.database.hosting}`);
      }
      sections.push('');
    }

    if (constitution.techStack.styling) {
      sections.push(`### Styling`);
      sections.push(`- Approach: ${constitution.techStack.styling.approach}`);
      if (constitution.techStack.styling.uiLibrary) {
        sections.push(
          `- UI Library: ${constitution.techStack.styling.uiLibrary}`,
        );
      }
      sections.push('');
    }

    if (constitution.techStack.keyDependencies?.length) {
      sections.push(`### Key Dependencies`);
      constitution.techStack.keyDependencies.forEach((dep) => {
        sections.push(`- ${dep}`);
      });
      sections.push('');
    }
  }

  // Quality Standards (from constitution)
  if (constitution?.qualityStandards) {
    sections.push('## Quality Gates');

    if (constitution.qualityStandards.accessibility) {
      sections.push(`### Accessibility`);
      sections.push(
        `- WCAG Level: ${constitution.qualityStandards.accessibility.wcagLevel}`,
      );
      if (constitution.qualityStandards.accessibility.requirements?.length) {
        constitution.qualityStandards.accessibility.requirements.forEach(
          (req) => {
            sections.push(`- ${req}`);
          },
        );
      }
      sections.push('');
    }

    if (constitution.qualityStandards.performance) {
      sections.push(`### Performance`);
      if (constitution.qualityStandards.performance.bundleSizeLimit) {
        sections.push(
          `- Bundle Size: ${constitution.qualityStandards.performance.bundleSizeLimit}`,
        );
      }
      if (constitution.qualityStandards.performance.ttfbTarget) {
        sections.push(
          `- TTFB Target: ${constitution.qualityStandards.performance.ttfbTarget}`,
        );
      }
      if (constitution.qualityStandards.performance.lcpTarget) {
        sections.push(
          `- LCP Target: ${constitution.qualityStandards.performance.lcpTarget}`,
        );
      }
      sections.push('');
    }

    if (constitution.qualityStandards.security) {
      sections.push(`### Security`);
      if (constitution.qualityStandards.security.authentication) {
        sections.push(
          `- Authentication: ${constitution.qualityStandards.security.authentication}`,
        );
      }
      if (constitution.qualityStandards.security.authorization) {
        sections.push(
          `- Authorization: ${constitution.qualityStandards.security.authorization}`,
        );
      }
      sections.push('');
    }

    if (constitution.qualityStandards.testing) {
      sections.push(`### Testing`);
      if (constitution.qualityStandards.testing.unitCoverage) {
        sections.push(
          `- Unit Coverage: ${constitution.qualityStandards.testing.unitCoverage}`,
        );
      }
      if (constitution.qualityStandards.testing.integrationRequired) {
        sections.push(`- Integration Tests: Required`);
      }
      if (constitution.qualityStandards.testing.e2eRequired) {
        sections.push(`- E2E Tests: Required`);
      }
      sections.push('');
    }
  }

  // Implementation Phases
  sections.push('## Implementation Phases');
  sections.push('');
  sections.push('Follow these phases in order:');
  sections.push('');

  if (artifacts.techSpec) {
    sections.push('### Phase 1: Core Architecture');
    sections.push(
      'Implement the foundational architecture as specified in the Tech Spec.',
    );
    sections.push('');
    sections.push('**Key tasks:**');
    sections.push('- Set up project structure following naming conventions');
    sections.push('- Configure build tools and dependencies');
    sections.push('- Implement core architectural patterns');
    sections.push('- Set up state management');
    sections.push('');
  }

  if (artifacts.userStories) {
    sections.push('### Phase 2: Feature Implementation');
    sections.push('Implement features based on User Stories.');
    sections.push('');
    sections.push('**Key tasks:**');
    sections.push('- Implement user-facing features');
    sections.push('- Build UI components with accessibility in mind');
    sections.push('- Integrate with backend APIs');
    sections.push('- Write unit tests for each feature');
    sections.push('');
  }

  if (constitution?.forbiddenPatterns?.length) {
    sections.push('### Phase 3: Quality Assurance');
    sections.push('');
    sections.push('**Before completing, verify:**');
    sections.push('- [ ] All quality gates from the Constitution are met');
    sections.push('- [ ] No forbidden patterns are used');
    sections.push('- [ ] Security requirements are implemented');
    sections.push('- [ ] Performance budgets are respected');
    sections.push('- [ ] Accessibility standards are met');
    sections.push('');
  }

  // Constraints & Patterns
  if (
    constitution?.namingConventions ||
    constitution?.forbiddenPatterns?.length
  ) {
    sections.push('## Constraints & Patterns');
    sections.push('');

    if (constitution.namingConventions) {
      sections.push('### Naming Conventions');
      if (constitution.namingConventions.files) {
        sections.push(
          `**Files:** ${JSON.stringify(constitution.namingConventions.files)}`,
        );
      }
      if (constitution.namingConventions.components) {
        sections.push(
          `**Components:** ${constitution.namingConventions.components}`,
        );
      }
      if (constitution.namingConventions.functions) {
        sections.push(
          `**Functions:** ${constitution.namingConventions.functions}`,
        );
      }
      sections.push('');
    }

    if (constitution.forbiddenPatterns?.length) {
      sections.push('### Forbidden Patterns');
      sections.push('**NEVER use these:**');
      sections.push('');
      constitution.forbiddenPatterns.forEach((pattern) => {
        sections.push(`- **${pattern.pattern}**`);
        sections.push(`  - Reason: ${pattern.reason}`);
        sections.push(`  - Alternative: ${pattern.alternative}`);
        sections.push('');
      });
    }
  }

  // Reference Materials
  sections.push('## Reference Materials');
  sections.push('');
  if (artifacts.prd) {
    sections.push('- **PRD:** Product requirements and user needs');
  }
  if (artifacts.techSpec) {
    sections.push('- **Tech Spec:** Technical implementation details');
  }
  if (artifacts.userStories) {
    sections.push('- **User Stories:** Acceptance criteria and user flows');
  }
  sections.push('');

  // Getting Started
  sections.push('## Getting Started');
  sections.push('');
  sections.push('1. Review this entire SKILL.md file');
  sections.push('2. Check the Constitution for architectural decisions');
  sections.push('3. Follow Implementation Phases in order');
  sections.push('4. Run quality checks after each phase');
  sections.push('5. Reference User Stories for acceptance criteria');
  sections.push('');

  return sections.join('\n');
}

/**
 * Parsed constitution structure
 */
interface ParsedConstitution {
  lockedConstraints?: {
    stateInvariants?: string[];
    domainRules?: string[];
    securityProtocols?: string[];
  };
  architecture?: {
    pattern?: string;
    rationale?: string;
    stateManagement?: string;
    apiDesign?: string;
  };
  techStack?: {
    frontend?: {
      framework?: string;
      version?: string;
      language?: string;
    };
    backend?: {
      runtime?: string;
      framework?: string;
      version?: string;
    };
    database?: {
      type?: string;
      orm?: string;
      hosting?: string;
    };
    styling?: {
      approach?: string;
      uiLibrary?: string;
    };
    keyDependencies?: string[];
  };
  qualityStandards?: {
    accessibility?: {
      wcagLevel?: string;
      requirements?: string[];
    };
    performance?: {
      bundleSizeLimit?: string;
      ttfbTarget?: string;
      lcpTarget?: string;
    };
    security?: {
      authentication?: string;
      authorization?: string;
    };
    testing?: {
      unitCoverage?: string;
      integrationRequired?: boolean;
      e2eRequired?: boolean;
    };
  };
  namingConventions?: {
    files?: Record<string, string>;
    components?: string;
    functions?: string;
    variables?: string;
    constants?: string;
  };
  forbiddenPatterns?: Array<{
    pattern: string;
    reason: string;
    alternative: string;
  }>;
  /** Raw content when JSON parsing fails */
  _raw?: string;
}

/**
 * Attempts to parse constitution JSON
 * Returns null on failure but logs the error for debugging
 */
function parseConstitution(
  constitutionContent: string,
): ParsedConstitution | null {
  try {
    // Try to extract JSON from markdown code blocks or raw JSON
    const jsonMatch = constitutionContent.match(/```(?:json)?\s*([\s\S]*?)```/);
    const jsonString = jsonMatch ? jsonMatch[1] : constitutionContent;

    return JSON.parse(jsonString.trim()) as ParsedConstitution;
  } catch (error) {
    console.warn(
      '[parseConstitution] Failed to parse constitution JSON, will include raw content for debugging. Error:',
      error,
    );
    // Return a minimal structure with raw content so it's not completely lost
    return {
      _raw:
        constitutionContent.substring(0, 2000) +
        (constitutionContent.length > 2000 ? '...' : ''),
    } as unknown as ParsedConstitution;
  }
}

/**
 * Converts a string to kebab-case
 */
function kebabCase(str: string): string {
  return str
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/[\s_]+/g, '-')
    .toLowerCase();
}

/**
 * Exports SKILL.md content for download
 */
export function exportSkillMd(input: SkillMdInput): {
  filename: string;
  content: string;
} {
  const kebabName = kebabCase(input.project.title);
  const content = generateSkillMd(input);

  return {
    filename: `${kebabName}-skill.md`,
    content,
  };
}
