"use client";

import { motion } from "framer-motion";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background pt-24 pb-20 px-6">
      <div className="max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-6xl md:text-8xl font-bold uppercase tracking-tighter mb-12">
            Terms of <span className="text-primary">Service</span>
          </h1>

          <div className="space-y-12 text-zinc-400 font-medium leading-relaxed">
            <section>
              <h2 className="text-2xl font-bold uppercase tracking-tight text-foreground mb-4 border-l-4 border-primary pl-4">
                1. The Engine
              </h2>
              <p>
                SpecForge is a high-performance project generation platform. By executing the protocol (accessing the service), you agree to be bound by these Terms. If you do not agree, cease operation immediately.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold uppercase tracking-tight text-foreground mb-4 border-l-4 border-primary pl-4">
                2. Ownership of Output
              </h2>
              <p>
                We believe in developer sovereignty. Subject to your compliance with these terms, SpecForge assigns all rights, title, and interest in the technical specifications, PRDs, and architecture documents generated by the system ("Artifacts") to you. You are the architect; we are the forge.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold uppercase tracking-tight text-foreground mb-4 border-l-4 border-primary pl-4">
                3. AI Disclosure
              </h2>
              <p>
                SpecForge utilizes elite Large Language Models (LLMs) to process data and forge artifacts. While our system is designed for extreme precision, we do not guarantee the absolute accuracy or safety of AI-generated content. All outputs must be audited by qualified engineering personnel before deployment into critical systems.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold uppercase tracking-tight text-foreground mb-4 border-l-4 border-primary pl-4">
                4. Credentials & Encryption
              </h2>
              <p>
                Users are solely responsible for the security of API keys provided to the system. SpecForge employs industrial-grade encryption for stored credentials. We are not liable for any unauthorized access resulting from user negligence or leaks from third-party LLM providers.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-bold uppercase tracking-tight text-foreground mb-4 border-l-4 border-primary pl-4">
                5. Prohibited Use
              </h2>
              <p>
                The Service shall not be used to generate malicious scripts, exploit vulnerabilities, or infringe upon the intellectual property of others. Any breach of this protocol results in immediate termination of access.
              </p>
            </section>

            <section className="pt-8 border-t border-border">
              <p className="text-xs uppercase tracking-widest">
                Last Updated: January 14, 2026 // End of Protocol
              </p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
