import { marked } from "marked";
import sanitizeHtml from "sanitize-html";
import { slugifyHeading } from "./spec-outline";

/**
 * Markdown rendering for specifications.
 *
 * Two entry points. `renderMarkdownSafe` renders public or reused content and stays permissive
 * about structure. `renderSpecHtml` renders the document surface and additionally gives every
 * heading a stable anchor id, so a clause can be linked and cited.
 */

const ALLOWED_TAGS = [
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "p",
  "ul",
  "ol",
  "li",
  "strong",
  "em",
  "code",
  "pre",
  "blockquote",
  "hr",
  "br",
  "a",
  "table",
  "thead",
  "tbody",
  "tfoot",
  "caption",
  "tr",
  "th",
  "td",
];

const SANITIZE_OPTIONS: sanitizeHtml.IOptions = {
  allowedTags: ALLOWED_TAGS,
  allowedAttributes: {
    a: ["href", "title", "rel", "target"],
  },
  allowedSchemes: ["http", "https", "mailto"],
  transformTags: {
    a: sanitizeHtml.simpleTransform(
      "a",
      { rel: "noopener noreferrer", target: "_blank" },
      true
    ),
  },
};

const HEADING_ID_OPTIONS: sanitizeHtml.IOptions = {
  ...SANITIZE_OPTIONS,
  allowedAttributes: {
    ...SANITIZE_OPTIONS.allowedAttributes,
    h1: ["id"],
    h2: ["id"],
    h3: ["id"],
    h4: ["id"],
  },
};

export function renderMarkdownSafe(markdown: string): string {
  const raw = marked.parse(markdown) as string;
  return sanitizeHtml(raw, SANITIZE_OPTIONS);
}

export function renderPreviewHtml(markdown: string): string {
  return renderMarkdownSafe(markdown);
}

/** Heading ids are generated by us, so anything else is rejected rather than trusted. */
const SAFE_ID = /^[a-z0-9][a-z0-9-]*$/i;
const HEADING = /<h([1-4])>([\s\S]*?)<\/h\1>/g;
/** Any attribute a content-authored heading carries. Anchor ids are ours, so these are stripped. */
const HEADING_ATTRS = /<h([1-4])[^>]*>/g;
/**
 * A claim bullet as `formatClaimManifest` writes it.
 *
 * The `(?:<p>)?` is load-bearing. `marked` renders a tight list as `<li><strong>…` but a loose one,
 * with a blank line between bullets, as `<li><p><strong>…`, and the first draft matched only the
 * tight form. A generated manifest with blank lines lost every evidence spine while the gap map
 * still reported the claim count, which is worse than either failing alone.
 */
const CLAIM_BULLET = /<li>(\s*(?:<p>)?\s*)<strong>([A-Za-z][A-Za-z0-9]*-\d+)<\/strong>/g;
const SAFE_CLAIM_ID = /^[A-Za-z][A-Za-z0-9]*-\d+$/;

/**
 * A heading that has an id, so a quality mark can be attached to the right clause.
 *
 * The id is required in the match: an unanchored heading is not a clause the table of contents knows
 * about, so there is nothing to mark it against.
 */
const ANCHORED_HEADING = /<h([1-4]) id="([^"]+)">([\s\S]*?)<\/h\1>/g;

/**
 * The vocabulary of a section mark, mapped to the word the reader sees.
 *
 * A caller names a token from this set and this module owns the wording, so a mark cannot arrive as
 * arbitrary text. The reader gets a word rather than a colour, which is the document language's rule.
 */
const SECTION_MARK_WORDS = {
  'over-budget': 'over budget',
  empty: 'empty',
} as const;

export type SectionMark = keyof typeof SECTION_MARK_WORDS;

/** The shape `sectionMarksFor` needs, declared structurally so this module owes nothing to the report. */
export interface MarkableSection {
  headingKey: string | null;
  empty: boolean;
  overBudget: boolean;
}

/**
 * Which marks to place, keyed by anchor id.
 *
 * A section can qualify for both marks at once: prose with no requirement behind it, written long.
 * The over-budget mark wins, because trimming is the action and the coverage line already counts
 * empties. Two marks on one heading, or a mark that replaced a count the reader was given, would be
 * the same information twice in the place where the document is least able to afford it.
 */
export function sectionMarksFor(
  sections: readonly MarkableSection[]
): Record<string, SectionMark> {
  const marks: Record<string, SectionMark> = {};

  for (const section of sections) {
    if (!section.headingKey) continue;
    if (section.overBudget) marks[section.headingKey] = 'over-budget';
    else if (section.empty) marks[section.headingKey] = 'empty';
  }

  return marks;
}

/**
 * Append a mark to the headings named in `sectionMarks`, keyed by anchor id.
 *
 * Applied after sanitising, for the same reason claim states are: sanitising strips unknown
 * attributes and elements, so a mark inserted earlier would be removed. The token is constrained to
 * the vocabulary above and the id has already passed `SAFE_ID` when the heading was anchored, so
 * nothing here can introduce markup a caller chose.
 *
 * A space separates the mark from the heading's text. A heading's accessible name is its text
 * content, so without it a reader hears "Problem Statementover budget" as one word. The rule that
 * styles the span adds a small margin on top, so the reader sees a deliberate gap rather than a
 * rendered space.
 */
function applySectionMarks(
  html: string,
  sectionMarks: Readonly<Record<string, SectionMark>>
): string {
  return html.replace(ANCHORED_HEADING, (match, level: string, id: string, inner: string) => {
    const token = sectionMarks[id];
    const word = token ? SECTION_MARK_WORDS[token] : undefined;
    if (!word) return match;

    return `<h${level} id="${id}">${inner} <span class="section-mark">${word}</span></h${level}>`;
  });
}

function stripTags(html: string): string {
  return html.replace(/<[^>]*>/g, "");
}

/**
 * Render specification markdown with an anchor id on every level 1 to 4 heading.
 *
 * An id is derived from the heading's own text, not from its position, and is applied only when
 * `parseSpecOutline` produced the same id. Position was the first design and it was wrong:
 * `parseSpecOutline` deliberately skips a heading indented inside a list item and a heading inside a
 * blockquote, because that markdown belongs to the body, while `marked` renders both as real
 * headings. Every heading after such a line was therefore handed the previous heading's id, and the
 * last one got none, so the table of contents pointed at the wrong clause.
 *
 * Deriving the id from the text is stable under that disagreement: a heading the outline counted and
 * a heading it skipped produce the same slug either way, and a heading the outline never saw simply
 * gets no id. Duplicate headings are suffixed the way the outline suffixes them, so
 * "## Overview" twice yields `overview` and `overview-2` on both sides.
 *
 * `headingIds` is therefore an allowlist rather than a sequence. The consequence for a caller is that
 * a document no longer has to be rendered in one piece or in a known order, which removed the
 * `startIndex` cursor and its `countSpecHeadings` companion: both existed only to keep a positional
 * assignment aligned, and a cursor is exactly the thing that drifted.
 *
 * When claim states are supplied, each claim bullet is tagged with its state so the document can
 * draw the same evidence spine the reader learned elsewhere. Tagging happens after sanitising,
 * because sanitising strips unknown attributes; both the id and the state are constrained by a
 * regex or a union before they reach the markup.
 */
export function renderSpecHtml(
  markdown: string,
  headingIds: readonly string[],
  claimStates?: Readonly<Record<string, string>>,
  sectionMarks?: Readonly<Record<string, SectionMark>>
): string {
  const allowed = new Set(headingIds);
  const used = new Set<string>();
  const counters = new Map<string, number>();

  // Every heading is normalised to a bare tag first. A content-authored `<h2 id="x">` would
  // otherwise keep an id that could collide with one the table of contents promises to a clause.
  const raw = (marked.parse(markdown) as string).replace(
    HEADING_ATTRS,
    (_match, level: string) => `<h${level}>`
  );

  const withIds = raw.replace(HEADING, (match, level: string, inner: string) => {
    const base = slugifyHeading(stripTags(inner));
    if (base === "") return match;

    let count = counters.get(base) ?? 0;
    let candidate = count === 0 ? base : `${base}-${count + 1}`;
    while (used.has(candidate)) {
      count += 1;
      candidate = `${base}-${count + 1}`;
    }
    counters.set(base, count);
    used.add(candidate);

    if (!allowed.has(candidate) || !SAFE_ID.test(candidate)) return match;

    return `<h${level} id="${candidate}">${inner}</h${level}>`;
  });

  const safe = sanitizeHtml(withIds, HEADING_ID_OPTIONS);

  // Both tags are applied after sanitising, so neither can be stripped by it, and each is applied
  // independently of the other: a caller may want the length marks without claim states.
  // The local is deliberately not named `marked`, which is the parser this function calls above.
  const withMarks = sectionMarks ? applySectionMarks(safe, sectionMarks) : safe;

  if (!claimStates) return withMarks;

  return withMarks.replace(CLAIM_BULLET, (match, gap: string, claimId: string) => {
    const state = claimStates[claimId];

    if (!state || !SAFE_CLAIM_ID.test(claimId) || !SAFE_ID.test(state)) return match;

    return `<li data-claim="${claimId}" data-state="${state}">${gap}<strong>${claimId}</strong>`;
  });
}
