import { marked } from "marked";
import sanitizeHtml from "sanitize-html";
import { slugifyHeading } from "./spec-outline";

/**
 * Markdown rendering for specifications.
 *
 * Two entry points. `renderMarkdownSafe` renders public or reused content and stays permissive
 * about structure. `renderSpecHtml` renders the document surface and additionally gives every
 * heading a stable anchor id, so a clause can be linked and cited.
 */

const ALLOWED_TAGS = [
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "p",
  "ul",
  "ol",
  "li",
  "strong",
  "em",
  "code",
  "pre",
  "blockquote",
  "hr",
  "br",
  "a",
  "table",
  "thead",
  "tbody",
  "tfoot",
  "caption",
  "tr",
  "th",
  "td",
];

const SANITIZE_OPTIONS: sanitizeHtml.IOptions = {
  allowedTags: ALLOWED_TAGS,
  allowedAttributes: {
    a: ["href", "title", "rel", "target"],
  },
  allowedSchemes: ["http", "https", "mailto"],
  transformTags: {
    a: sanitizeHtml.simpleTransform(
      "a",
      { rel: "noopener noreferrer", target: "_blank" },
      true
    ),
  },
};

const HEADING_ID_OPTIONS: sanitizeHtml.IOptions = {
  ...SANITIZE_OPTIONS,
  allowedAttributes: {
    ...SANITIZE_OPTIONS.allowedAttributes,
    h1: ["id"],
    h2: ["id"],
    h3: ["id"],
    h4: ["id"],
  },
};

export function renderMarkdownSafe(markdown: string): string {
  const raw = marked.parse(markdown) as string;
  return sanitizeHtml(raw, SANITIZE_OPTIONS);
}

export function renderPreviewHtml(markdown: string): string {
  return renderMarkdownSafe(markdown);
}

/** Heading ids are generated by us, so anything else is rejected rather than trusted. */
const SAFE_ID = /^[a-z0-9][a-z0-9-]*$/i;
const HEADING = /<h([1-4])>([\s\S]*?)<\/h\1>/g;
/** Any attribute a content-authored heading carries. Anchor ids are ours, so these are stripped. */
const HEADING_ATTRS = /<h([1-4])[^>]*>/g;
/**
 * A claim bullet as `formatClaimManifest` writes it.
 *
 * The `(?:<p>)?` is load-bearing. `marked` renders a tight list as `<li><strong>…` but a loose one,
 * with a blank line between bullets, as `<li><p><strong>…`, and the first draft matched only the
 * tight form. A generated manifest with blank lines lost every evidence spine while the gap map
 * still reported the claim count, which is worse than either failing alone.
 */
const CLAIM_BULLET = /<li>(\s*(?:<p>)?\s*)<strong>([A-Za-z][A-Za-z0-9]*-\d+)<\/strong>/g;
const SAFE_CLAIM_ID = /^[A-Za-z][A-Za-z0-9]*-\d+$/;

function stripTags(html: string): string {
  return html.replace(/<[^>]*>/g, "");
}

/**
 * Render specification markdown with an anchor id on every level 1 to 4 heading.
 *
 * An id is derived from the heading's own text, not from its position, and is applied only when
 * `parseSpecOutline` produced the same id. Position was the first design and it was wrong:
 * `parseSpecOutline` deliberately skips a heading indented inside a list item and a heading inside a
 * blockquote, because that markdown belongs to the body, while `marked` renders both as real
 * headings. Every heading after such a line was therefore handed the previous heading's id, and the
 * last one got none, so the table of contents pointed at the wrong clause.
 *
 * Deriving the id from the text is stable under that disagreement: a heading the outline counted and
 * a heading it skipped produce the same slug either way, and a heading the outline never saw simply
 * gets no id. Duplicate headings are suffixed the way the outline suffixes them, so
 * "## Overview" twice yields `overview` and `overview-2` on both sides.
 *
 * `headingIds` is therefore an allowlist rather than a sequence. The consequence for a caller is that
 * a document no longer has to be rendered in one piece or in a known order, which removed the
 * `startIndex` cursor and its `countSpecHeadings` companion: both existed only to keep a positional
 * assignment aligned, and a cursor is exactly the thing that drifted.
 *
 * When claim states are supplied, each claim bullet is tagged with its state so the document can
 * draw the same evidence spine the reader learned elsewhere. Tagging happens after sanitising,
 * because sanitising strips unknown attributes; both the id and the state are constrained by a
 * regex or a union before they reach the markup.
 */
export function renderSpecHtml(
  markdown: string,
  headingIds: readonly string[],
  claimStates?: Readonly<Record<string, string>>
): string {
  const allowed = new Set(headingIds);
  const used = new Set<string>();
  const counters = new Map<string, number>();

  // Every heading is normalised to a bare tag first. A content-authored `<h2 id="x">` would
  // otherwise keep an id that could collide with one the table of contents promises to a clause.
  const raw = (marked.parse(markdown) as string).replace(
    HEADING_ATTRS,
    (_match, level: string) => `<h${level}>`
  );

  const withIds = raw.replace(HEADING, (match, level: string, inner: string) => {
    const base = slugifyHeading(stripTags(inner));
    if (base === "") return match;

    let count = counters.get(base) ?? 0;
    let candidate = count === 0 ? base : `${base}-${count + 1}`;
    while (used.has(candidate)) {
      count += 1;
      candidate = `${base}-${count + 1}`;
    }
    counters.set(base, count);
    used.add(candidate);

    if (!allowed.has(candidate) || !SAFE_ID.test(candidate)) return match;

    return `<h${level} id="${candidate}">${inner}</h${level}>`;
  });

  const safe = sanitizeHtml(withIds, HEADING_ID_OPTIONS);

  if (!claimStates) return safe;

  return safe.replace(CLAIM_BULLET, (match, gap: string, claimId: string) => {
    const state = claimStates[claimId];

    if (!state || !SAFE_CLAIM_ID.test(claimId) || !SAFE_ID.test(state)) return match;

    return `<li data-claim="${claimId}" data-state="${state}">${gap}<strong>${claimId}</strong>`;
  });
}
