import { marked } from "marked";
import sanitizeHtml from "sanitize-html";

/**
 * Markdown rendering for specifications.
 *
 * Two entry points. `renderMarkdownSafe` renders public or reused content and stays permissive
 * about structure. `renderSpecHtml` renders the document surface and additionally gives every
 * heading a stable anchor id, so a clause can be linked and cited.
 */

const ALLOWED_TAGS = [
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "p",
  "ul",
  "ol",
  "li",
  "strong",
  "em",
  "code",
  "pre",
  "blockquote",
  "hr",
  "br",
  "a",
  "table",
  "thead",
  "tbody",
  "tfoot",
  "caption",
  "tr",
  "th",
  "td",
];

const SANITIZE_OPTIONS: sanitizeHtml.IOptions = {
  allowedTags: ALLOWED_TAGS,
  allowedAttributes: {
    a: ["href", "title", "rel", "target"],
  },
  allowedSchemes: ["http", "https", "mailto"],
  transformTags: {
    a: sanitizeHtml.simpleTransform(
      "a",
      { rel: "noopener noreferrer", target: "_blank" },
      true
    ),
  },
};

const HEADING_ID_OPTIONS: sanitizeHtml.IOptions = {
  ...SANITIZE_OPTIONS,
  allowedAttributes: {
    ...SANITIZE_OPTIONS.allowedAttributes,
    h1: ["id"],
    h2: ["id"],
    h3: ["id"],
    h4: ["id"],
  },
};

export function renderMarkdownSafe(markdown: string): string {
  const raw = marked.parse(markdown) as string;
  return sanitizeHtml(raw, SANITIZE_OPTIONS);
}

export function renderPreviewHtml(markdown: string): string {
  return renderMarkdownSafe(markdown);
}

/** Heading ids are generated by us, so anything else is rejected rather than trusted. */
const SAFE_ID = /^[a-z0-9][a-z0-9-]*$/i;
const HEADING = /<h([1-4])>([\s\S]*?)<\/h\1>/g;
/** A claim bullet as `formatClaimManifest` writes it. */
const CLAIM_BULLET = /<li>(\s*)<strong>([A-Za-z][A-Za-z0-9]*-\d+)<\/strong>/g;
const SAFE_CLAIM_ID = /^[A-Za-z][A-Za-z0-9]*-\d+$/;

/**
 * Render specification markdown with an anchor id on every level 1 to 4 heading. Ids are applied in
 * document order, which is the same order `parseSpecOutline` reports them, so a table of contents
 * built from the outline points at the right clauses.
 *
 * When claim states are supplied, each claim bullet is tagged with its state so the document can
 * draw the same evidence spine the reader learned elsewhere. Tagging happens after sanitising,
 * because sanitising strips unknown attributes; both the id and the state are constrained by a
 * regex or a union before they reach the markup.
 *
 * `startIndex` lets a caller render one document in several pieces and still keep the ids in
 * document order: the reading surface splits the body at mermaid fences, so each piece resumes
 * where the previous one stopped. `countSpecHeadings` reports how far to advance.
 */
export function renderSpecHtml(
  markdown: string,
  headingIds: readonly string[],
  claimStates?: Readonly<Record<string, string>>,
  startIndex = 0
): string {
  const raw = marked.parse(markdown) as string;
  let index = startIndex;

  const withIds = raw.replace(HEADING, (match, level: string, inner: string) => {
    const id = headingIds[index];
    index += 1;

    if (!id || !SAFE_ID.test(id)) return match;

    return `<h${level} id="${id}">${inner}</h${level}>`;
  });

  const safe = sanitizeHtml(withIds, HEADING_ID_OPTIONS);

  if (!claimStates) return safe;

  return safe.replace(CLAIM_BULLET, (match, gap: string, claimId: string) => {
    const state = claimStates[claimId];

    if (!state || !SAFE_CLAIM_ID.test(claimId) || !SAFE_ID.test(state)) return match;

    return `<li data-claim="${claimId}" data-state="${state}">${gap}<strong>${claimId}</strong>`;
  });
}

/** Every level 1 to 4 heading the produced html carries, whether or not an id was applied. */
const RENDERED_HEADING = /<h[1-4][ >]/g;

/**
 * How many entries of `headingIds` a `renderSpecHtml` call consumed. A heading advances the index
 * even when it is left without an id, so this counts the rendered tags rather than the applied ids.
 * A caller rendering a document in pieces advances its cursor by this count.
 */
export function countSpecHeadings(html: string): number {
  return html.match(RENDERED_HEADING)?.length ?? 0;
}
